apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-14T06:54:48Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "7865"
  uid: 6ea0069b-150f-4beb-9a44-b8e62fcef12c
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.111.123.61
  clusterIPs:
  - 10.111.123.61
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31940
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}